# 项目的唯一标识，必须与 SonarQube 服务器上创建的项目 Key 一致
sonar.projectKey=Notesmaster

# 项目名称
sonar.projectName=Notesmaster

# 项目版本
sonar.projectVersion=1.0

# 源代码的目录 (你的Android项目代码在这里)
sonar.sources=app/src/main/java

# 编译后的字节码文件目录 (SonarScanner需要分析.class文件)
sonar.java.binaries=app/build/intermediates/javac

# 核心配置：SonarQube 服务器的地址
# 因为你的Docker容器可以映射端口，所以Windows直接用 localhost 就能访问到WSL里的服务
sonar.host.url=http://localhost:9000

# 登录认证
sonar.login=admin
sonar.password=3180681581

# 编码格式
sonar.sourceEncoding=UTF-8